defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "pages"
    values:
      layout: "default"

permalink: /:categories/:title/

highlighter: using_prism_thanks
