defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "basic"

url: https://stolley.dev

permalink: /:categories/:title/

highlighter: using_prism_thanks

exclude:
  - backstop_data
  - backstop.json
  - Rakefile
  - Gemfile*
