defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "basic"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

url: https://stolley.dev

permalink: /:categories/:title/

highlighter: using_prism_thanks

include:
  - .well-known

exclude:
  - backstop_data
  - backstop.json
  - Rakefile
  - Gemfile*
