defaults:
  -
    scope:
      path: ""
    values:
      layout: "basic"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
      category: "linked"
    values:
      layout: "linked"

url: stolley.dev

permalink: /:categories/:title/

highlighter: using_prism_thanks

exclude:
  - backstop_data
  - backstop.json
  - Rakefile
  - Gemfile*
